name: Build Polyglot Book

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-book:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install python-chess

      - name: Combine PGNs
        run: |
          cat MaggiChess16.pgn NNUE_Drift.pgn NimsiluBot.pgn ToromBot.pgn Endogenetic-Bot.pgn > combined.pgn
          echo "Combined PGNs into combined.pgn"

      - name: Build book
        run: |
          python create_polyglot.py

      - name: Upload book.bin
        uses: actions/upload-artifact@v4
        with:
          name: polyglot-book
          path: book.bin
