name: Run Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'  

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Add timeout

    concurrency:
      group: bot-restart
      cancel-in-progress: false

    env:
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Setup Actions
        uses: actions/checkout@v4  # Updated version

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Verify config.yml exists
        run: |
          if [ ! -f config.yml ]; then
            echo "config.yml not found!"
            exit 1
          fi
          echo "Original config.yml:"
          cat config.yml

      - name: Fetch Token
        run: |
          sed -i "s/^token:.*/token: \"${TOKEN}\"/" config.yml
          echo "Updated config.yml:"
          cat config.yml

      - name: Download latest Stockfish dev 
        run: |
          mkdir -p engines
          curl -L -o stockfish.zip http://abrok.eu/stockfish/latest/linux/stockfish_x64_modern.zip
          unzip -o stockfish.zip -d engines/
          ls -la engines/
          mv engines/stockfish_* engines/stockfish || echo "No stockfish file to rename"
          chmod +x engines/stockfish
          ./engines/stockfish --help || echo "Stockfish test failed"

      - name: Run Bot
        run: |
          echo "Starting bot..."
          timeout 20700 python3 -u user_interface.py "matchmaking" || echo "Bot process ended"

      - name: 🔁 Self-Restart (Fire-and-Forget)
        if: always()
        run: |
          gh workflow run bot.yml  # Make sure this matches your actual filename
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
