name: Add Suprabot Syzygy Tablebases

on:
  workflow_dispatch:

jobs:
  add-syzygy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: mkdir -p engines/syzygy

      - run: |
          cd engines/syzygy
          # Download all RTBW and RTBZ files from Suprabot repo
          wget -r -np -nH --cut-dirs=5 -A "*.rtbw,*.rtbz" https://github.com/suprateem-ux/suprabot/raw/main/engines/syzygy/

      - run: |
          git add engines/syzygy/*
          git commit -m "Add actual Suprabot Syzygy binaries"
          git push origin main
