name: Add Lichess OVH Standard Syzygy Tablebases

on:
  workflow_dispatch:

jobs:
  add-syzygy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs wget unzip
          git lfs install

      - run: mkdir -p engines/syzygy

      - run: |
          cd engines/syzygy
          for type in WDL DTZ; do
            for pieces in 3 4 5; do
              wget https://tablebase.lichess.ovh/tables/standard/${pieces}pieces/${type}/index.json -O index.json
              cat index.json | grep -oP '"url":"\K[^"]+' > urls.txt
              wget -i urls.txt
              rm index.json urls.txt
            done
          done

      - run: |
          git lfs track "engines/syzygy/**"
          git add .gitattributes

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add engines/syzygy/*
          git commit -m "Add Lichess OVH standard Syzygy tablebases 3-5 pieces WDL+DTZ"
          git push origin main
