name: Add Syzygy Tablebases

on:
  workflow_dispatch:

jobs:
  add-syzygy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs unzip wget
          git lfs install

      - name: Create syzygy folder
        run: mkdir -p engines/syzygy

      - name: Download Syzygy tablebases
        run: |
          cd engines/syzygy
          
          # Define arrays of pieces and types
          PIECES=("3-4" "5")
          TYPES=("WDL" "DTZ")
          
          for p in "${PIECES[@]}"; do
            for t in "${TYPES[@]}"; do
              echo "Downloading $p/$t files..."
              # Download all .zip files from Lichess tablebase
              wget -r -np -nH --cut-dirs=3 -R "index.html*" "https://tablebase.lichess.ovh/tables/$p/$t/"
            done
          done

          # Unzip all downloaded files and remove zips
          find . -name "*.zip" -exec unzip -o {} \; -exec rm {} \;

      - name: Track with Git LFS
        run: |
          git lfs track "engines/syzygy/**"
          git add .gitattributes

      - name: Commit and push Syzygy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add engines/syzygy/*
          git commit -m "Add full Syzygy tablebases (3-5 pieces, WDL + DTZ)"
          git push origin main
